In [1]:
# Cell 1 - Setup
%config InlineBackend.figure_format = 'retina'

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
import plotly.graph_objects as go

# Load .env from project root (you uploaded this file)
load_dotenv()   # reads .env (DB_USER, DB_PASSWORD, ...). See uploaded .env. :contentReference[oaicite:12]{index=12}

DB_USER = os.getenv("DB_USER", "itumeleng")
DB_PASSWORD = os.getenv("DB_PASSWORD", "libra")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "bank_analytics")

engine = create_engine(f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")
print("Connected to:", DB_NAME, "as", DB_USER)

Connected to: bank_analytics as itumeleng

In [3]:
# Cell 2 - SQL Queries (run & preview)
import pandas as pd

# Query A: CAC + Conversion by acquisition channel
sql_cac = """
SELECT
  acquisition_channel,
  SUM(acquisition_cost) AS total_spend,
  SUM(new_users) AS total_new_users,
  ROUND(SUM(acquisition_cost)::numeric / NULLIF(SUM(new_users),0), 2) AS cac,
  ROUND(AVG(CASE WHEN new_users>0 THEN (first_deposit_users::numeric / NULLIF(new_users,0)) END) * 100, 2) AS conversion_rate_pct
FROM raw.user_acquisition
GROUP BY acquisition_channel
ORDER BY conversion_rate_pct DESC;
"""

# Query B: Monthly churn rate (from raw.churn)
sql_churn = """
SELECT
  month,
  churned_users,
  total_users_start,
  ROUND(churned_users::numeric / NULLIF(total_users_start,0) * 100, 2) AS churn_rate_pct
FROM raw.churn
ORDER BY month;
"""

# Query C: LTV Proxy Fallback (Since user-level joins are not possible with current data)
# This calculates an average revenue proxy per user acquired for each channel based on total channel activity.
# It assumes revenue in a given month can be attributed to users acquired via channels active that month.
# This is a simplified proxy and has significant limitations compared to user-level analysis.
sql_ltv_proxy_fallback = """
WITH monthly_channel_totals AS (
  SELECT
    ua.month,
    ua.acquisition_channel,
    SUM(ua.new_users) AS new_users_in_month,
    SUM(t.total_revenue) AS total_revenue_in_month
  FROM raw.user_acquisition ua
  JOIN raw.transactions t ON ua.month = t.month
  GROUP BY ua.month, ua.acquisition_channel
),
channel_aggregates AS (
  SELECT
    acquisition_channel,
    SUM(new_users_in_month) AS total_users_acquired,
    SUM(total_revenue_in_month) AS total_revenue_attributable,
    -- Calculate total revenue attributed to channel / total users acquired for that channel
    -- This gives a very rough average revenue per acquired user across all months
    -- It's a proxy and doesn't account for time-value or individual user behavior
    COALESCE(
      SUM(total_revenue_in_month)::numeric / NULLIF(SUM(new_users_in_month), 0), 0
    ) AS avg_revenue_per_acquired_user
  FROM monthly_channel_totals
  GROUP BY acquisition_channel
)
SELECT
  acquisition_channel,
  total_users_acquired,
  ROUND(total_revenue_attributable, 2) AS total_revenue_attributed,
  ROUND(avg_revenue_per_acquired_user, 2) AS avg_revenue_per_acquired_user_proxy,
  -- A simple LTV proxy: avg_revenue_per_acquired_user * assumed_customer_lifetime_months
  -- Here we use 12 months as an example, adjust as needed or make it a parameter
  ROUND(avg_revenue_per_acquired_user * 12, 2) AS ltv_12_month_proxy
FROM channel_aggregates
ORDER BY avg_revenue_per_acquired_user_proxy DESC;
"""

# Run queries and show
print("--- Executing CAC & Conversion Query ---")
cac_df = pd.read_sql(sql_cac, engine)
print("CAC & Conversion by Channel")
display(cac_df)

print("\n--- Executing Monthly Churn Query ---")
churn_df = pd.read_sql(sql_churn, engine)
print("Monthly Churn")
display(churn_df.head(12))

print("\n--- Executing LTV Proxy Fallback Query ---")
# Use the fallback query directly, as the user-level join is not possible
ltv_df = pd.read_sql(sql_ltv_proxy_fallback, engine)

print("LTV Proxy Fallback (Channel-Level Revenue/Attribution)")
display(ltv_df.head(10))

# Optional: Print the column names to confirm
print("\n--- Column Names ---")
print("CAC/Conversion Table Columns:", list(cac_df.columns))
print("Churn Table Columns:", list(churn_df.columns))
print("LTV Table Columns:", list(ltv_df.columns))

--- Executing CAC & Conversion Query ---
CAC & Conversion by Channel

  acquisition_channel  total_spend  total_new_users   cac  conversion_rate_pct
0            Referral     280800.0          14040.0  20.0                84.99
1         Paid Search    1065150.0          23670.0  45.0                68.58
2             Organic          0.0          19715.0   0.0                65.67
3        Social Media    1035930.0          24665.0  42.0                63.33

--- Executing Monthly Churn Query ---
Monthly Churn

         month  churned_users  total_users_start  churn_rate_pct
0   2024-01-01           2500              45000            5.56
1   2024-02-01           2830              49700            5.69
2   2024-03-01           3000              54870            5.47
3   2024-04-01           3170              60635            5.23
4   2024-05-01           3230              67065            4.82
5   2024-06-01           3350              74015            4.53
6   2024-07-01           3700              80920            4.57
7   2024-08-01           4300              87920            4.89
8   2024-09-01           4950              95215            5.20
9   2024-10-01           5750             102705            5.60
10  2024-11-01           6850             110460            6.20
11  2024-12-01           8150             118570            6.87

--- Executing LTV Proxy Fallback Query ---
LTV Proxy Fallback (Channel-Level Revenue/Attribution)

,acquisition_channel,total_users_acquired,total_revenue_attributed,avg_revenue_per_acquired_user_proxy,ltv_12_month_proxy
0,Referral,14040.0,3261700.0,232.31,2787.78
1,Organic,19715.0,3261700.0,165.44,1985.31
2,Paid Search,23670.0,3261700.0,137.80,1653.59
3,Social Media,24665.0,3261700.0,132.24,1586.88

--- Column Names ---
CAC/Conversion Table Columns: ['acquisition_channel', 'total_spend', 'total_new_users', 'cac', 'conversion_rate_pct']
Churn Table Columns: ['month', 'churned_users', 'total_users_start', 'churn_rate_pct']
LTV Table Columns: ['acquisition_channel', 'total_users_acquired', 'total_revenue_attributed', 'avg_revenue_per_acquired_user_proxy', 'ltv_12_month_proxy']

In [30]:
# Annotated churn chart (high-resolution)
import os
import pandas as pd
from sqlalchemy import create_engine
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# DB connection (change if you store credentials elsewhere)
engine = create_engine("postgresql://itumeleng:libra@localhost:5432/bank_analytics")

sql = """
SELECT
  month::date AS month,
  churned_users,
  total_users_start,
  ROUND( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0, 2) AS churn_rate_pct,
  ROUND(
    LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month)::numeric,
    2
  ) AS prev_churn_rate_pct,
  ROUND(
    ( ( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 )
      - LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month)
    )::numeric
    , 2
  ) AS mom_abs_change_pct,
  ROUND(
    CASE
      WHEN LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month) IS NULL
        THEN NULL
      WHEN LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month) = 0
        THEN NULL
      ELSE
        (
          ( ( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 )
            - LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month)
          )
          / NULLIF(LAG( (churned_users::numeric / NULLIF(total_users_start,0)) * 100.0 ) OVER (ORDER BY month), 0)
        ) * 100.0
    END
    , 1
  ) AS mom_rel_change_pct,
  CASE WHEN month::date >= '2024-08-01' THEN 'CRISIS_PERIOD' ELSE 'NORMAL' END AS period_type
FROM raw.churn
ORDER BY month;
"""

df = pd.read_sql(sql, engine)
df['month'] = pd.to_datetime(df['month'])
df = df.sort_values('month').reset_index(drop=True)

# Identify extremes and important points
idx_max = df['churn_rate_pct'].idxmax()
idx_min = df['churn_rate_pct'].idxmin()
max_row = df.loc[idx_max]
min_row = df.loc[idx_min]
latest_row = df.iloc[-1]

# Plot settings (Knaflic palette)
COLORS = {
    'context': '#D3D3D3',
    'problem': '#E63946',
    'primary': '#2E86AB',
    'text': '#2B2B2B'
}

# Create figure
fig = go.Figure()

# Background (context) - all points grey first
fig.add_trace(go.Scatter(
    x=df['month'],
    y=df['churn_rate_pct'],
    mode='lines',
    line=dict(color=COLORS['context'], width=2),
    hoverinfo='skip',
    name='Context'
))

# Emphasize crisis period (period_type == 'CRISIS_PERIOD')
if 'period_type' in df.columns:
    crisis_df = df[df['period_type'] == 'CRISIS_PERIOD']
    normal_df = df[df['period_type'] != 'CRISIS_PERIOD']
    # normal line (thin)
    fig.add_trace(go.Scatter(
        x=normal_df['month'],
        y=normal_df['churn_rate_pct'],
        mode='lines+markers',
        line=dict(color=COLORS['context'], width=2),
        marker=dict(size=6, color=COLORS['context']),
        name='Normal'
    ))
    # crisis highlighted
    fig.add_trace(go.Scatter(
        x=crisis_df['month'],
        y=crisis_df['churn_rate_pct'],
        mode='lines+markers+text',
        text=[f"{v:.1f}%" for v in crisis_df['churn_rate_pct']],
        textposition='top center',
        line=dict(color=COLORS['problem'], width=4),
        marker=dict(size=10, color=COLORS['problem']),
        name='Crisis period'
    ))
else:
    # if no period flag, just highlight last N months (e.g., last 6)
    n_highlight = min(6, len(df))
    fig.add_trace(go.Scatter(
        x=df['month'][:-n_highlight],
        y=df['churn_rate_pct'][:-n_highlight],
        mode='lines',
        line=dict(color=COLORS['context'], width=2),
        name='History'
    ))
    fig.add_trace(go.Scatter(
        x=df['month'][-n_highlight:],
        y=df['churn_rate_pct'][-n_highlight:],
        mode='lines+markers+text',
        text=[f"{v:.1f}%" for v in df['churn_rate_pct'][-n_highlight:]],
        textposition='top center',
        line=dict(color=COLORS['problem'], width=4),
        marker=dict(size=10, color=COLORS['problem']),
        name='Recent'
    ))

# Annotate max and min exactly
fig.add_annotation(
    x=max_row['month'],
    y=max_row['churn_rate_pct'],
    text=f"<b>Max: {max_row['churn_rate_pct']:.2f}%</b><br>{max_row['month'].strftime('%b %Y')}",
    showarrow=True,
    arrowhead=2,
    ax=0, ay=-60,
    font=dict(color=COLORS['text'])
)
fig.add_annotation(
    x=min_row['month'],
    y=min_row['churn_rate_pct'],
    text=f"Min: {min_row['churn_rate_pct']:.2f}%<br>{min_row['month'].strftime('%b %Y')}",
    showarrow=True,
    arrowhead=2,
    ax=0, ay=40,
    font=dict(color=COLORS['text'])
)

# Add % change annotation from first to last
first_val = df['churn_rate_pct'].iloc[0]
last_val = df['churn_rate_pct'].iloc[-1]
abs_diff = last_val - first_val
rel_diff_pct = (abs_diff / first_val * 100.0) if first_val != 0 else None

change_text = f"From {first_val:.2f}% → {last_val:.2f}%\nΔ = {abs_diff:+.2f} ppt"
if rel_diff_pct is not None:
    change_text += f" ({rel_diff_pct:+.1f}%)"

fig.add_annotation(
    x=df['month'].iloc[int(len(df)/2)],
    y=max(df['churn_rate_pct']) + 0.8,
    text=change_text,
    showarrow=False,
    bgcolor="rgba(255,255,255,0.9)",
    bordercolor=COLORS['text'],
    font=dict(color=COLORS['text'])
)

# Add horizontal threshold line (6%)
threshold = 6.0
fig.add_hline(y=threshold, line_dash="dot", line_color=COLORS['problem'],
              annotation_text=f"⚠️ {threshold:.1f}% Alert Threshold", annotation_position="right",
              annotation=dict(font_size=11, font_color=COLORS['problem']))

# Direct label last point prominently (callout)
fig.add_trace(go.Scatter(
    x=[latest_row['month']],
    y=[latest_row['churn_rate_pct']],
    mode='markers+text',
    marker=dict(size=14, color=COLORS['problem']),
    text=[f"{latest_row['churn_rate_pct']:.2f}%"],
    textposition='bottom center',
    hovertemplate=f"{latest_row['month'].strftime('%b %Y')}: {latest_row['churn_rate_pct']:.2f}%<extra></extra>",
    name='Latest'
))

# Layout - Knaflic style (title-as-story, minimal clutter)
fig.update_layout(
    title={
        'text': '<b>Churn Crisis — Rate Jumped From Baseline to Crisis</b><br><sub>Key: threshold, max, and percent-change annotated</sub>',
        'x':0, 'xanchor':'left'
    },
    xaxis_title="<b>Month (2024)</b>",
    yaxis_title="<b>Churn Rate (%)</b>",
    plot_bgcolor='white',
    paper_bgcolor='white',
    height=560,
    width=1100,
    margin=dict(l=60, r=40, t=110, b=60),
    font=dict(family='Arial', color=COLORS['text'])
)

# X axis formatting
fig.update_xaxes(tickformat='%b', showgrid=False, showline=True, linecolor='#E9E9E9')
fig.update_yaxes(showgrid=True, gridcolor='rgba(211,211,211,0.3)', zeroline=False, rangemode='tozero')

# Ensure outputs folder exists
os.makedirs('outputs', exist_ok=True)

# Save high-resolution PNG + SVG (requires kaleido)
fig.write_image("outputs/01_monthly_churn_annotated.png", scale=3, width=1650, height=840)  # high-res PNG
fig.write_image("outputs/01_monthly_churn_annotated.svg")  # vector for PPT if needed
print("Saved: outputs/01_monthly_churn_annotated.png and .svg")

# Show interactive figure
fig.show()

Saved: outputs/01_monthly_churn_annotated.png and .svg

In [19]:
# Cell 4 - Channel performance horizontal bar (clean, annotated)

try:
    channel_df = pd.read_sql("SELECT * FROM presentation.channel_with_emphasis ORDER BY display_order, conversion_rate DESC", engine)
    channel_df.rename(columns={'conversion_rate':'conversion_rate_pct'}, inplace=True)
    use_presentation = True
    print("Using presentation.channel_with_emphasis view.")
except sqlalchemy.exc.ProgrammingError: # Catch specific error for missing view/table
    channel_df = cac_df.copy()
    channel_df.rename(columns={'conversion_rate_pct':'conversion_rate_pct'}, inplace=True)
    use_presentation = False
    print("Using computed CAC table for plotting.")

# Colors: Referral = primary (blue), Social Media = problem (red), others grey
COL = {'primary': '#2E86AB', 'problem': '#E63946', 'context': '#D3D3D3'}
if 'visual_priority' in channel_df.columns:
    colors = [COL['primary'] if v=='PRIMARY' else COL['problem'] if v=='PROBLEM' else COL['context'] for v in channel_df.get('visual_priority', ['CONTEXT']*len(channel_df))]
else:
    colors = [COL['primary'] if ch=='Referral' else COL['problem'] if ch=='Social Media' else COL['context']
              for ch in channel_df[channel_df.columns[0]]]

fig2 = go.Figure()
fig2.add_trace(go.Bar(
    x=channel_df['conversion_rate_pct'],
    y=channel_df[channel_df.columns[0]],
    orientation='h',
    marker=dict(color=colors),
    text=[f"{x:.1f}%" for x in channel_df['conversion_rate_pct']],
    textposition='outside'
))

# Annotations - add for referral and social if present
if 'Referral' in channel_df.iloc[:,0].values:
    r = channel_df[channel_df.iloc[:,0]=='Referral'].iloc[0]
    fig2.add_annotation(x=r['conversion_rate_pct'], y='Referral',
                        text="<b>Referral: High conversion</b>", showarrow=True, arrowhead=2,
                        ax=-80, ay=-30, font=dict(color=COL['primary']))
if 'Social Media' in channel_df.iloc[:,0].values:
    s = channel_df[channel_df.iloc[:,0]=='Social Media'].iloc[0]
    fig2.add_annotation(x=s['conversion_rate_pct'], y='Social Media',
                        text="<b>Social: High spend, low ROI</b>", showarrow=True, arrowhead=2,
                        ax=80, ay=40, font=dict(color=COL['problem']))

fig2.update_layout(
    title="<b>Channel Conversion Rates — Highlighting Referral and Social Media</b>",
    xaxis_title='Conversion rate (%)',
    height=450,
    plot_bgcolor='white',
    showlegend=False
)
fig2.update_xaxes(range=[0, max(channel_df['conversion_rate_pct'].max()*1.1, 90)])
fig2.write_image("outputs/jupyter_channel_performance.png", scale=2)
fig2.show()
print("Saved: outputs/jupyter_channel_performance.png")

Using computed CAC table for plotting.

Saved: outputs/jupyter_channel_performance.png

In [4]:
# Cell 5 - LTV:CAC by channel (proxy)
# Try to build a dataframe with CAC and LTV estimate

# Get CAC table
cac = cac_df.copy()
cac = cac.set_index('acquisition_channel')

# Prepare ltv_df from earlier step (check for the correct column name from sql_ltv_proxy_fallback)
if 'acquisition_channel' in ltv_df.columns and 'avg_revenue_per_acquired_user_proxy' in ltv_df.columns:
    ltv_tmp = ltv_df.set_index('acquisition_channel')
    # Join CAC with the LTV proxy column calculated per channel
    combined = cac.join(ltv_tmp[['avg_revenue_per_acquired_user_proxy']], how='left')
    # Calculate 12-month LTV proxy using the column from the LTV query
    combined['ltv_12_month'] = combined['avg_revenue_per_acquired_user_proxy'].fillna(0) * 12
    print("Using LTV proxy from channel-level calculation.")
else:
    # Fallback: This block should ideally not run if sql_ltv_proxy_fallback worked correctly
    # If it did run, it means ltv_df structure was unexpected.
    # Let's try the fallback SQL query again, but with the correct column name 'total_revenue'
    print("LTV proxy calculation failed, attempting fallback SQL (using total_revenue).")
    median_revenue = 0
    try:
        # Use 'total_revenue' from raw.transactions
        tx_summary = pd.read_sql("SELECT month, SUM(total_revenue) as total_revenue FROM raw.transactions GROUP BY month", engine)
        total_users_acq_overall = cac['total_new_users'].sum() # Use total new users from cac_df as proxy denominator
        months_with_revenue = len(tx_summary[tx_summary['total_revenue'] > 0])
        if months_with_revenue > 0 and total_users_acq_overall > 0:
             # Calculate an *overall* revenue per user per month as a very rough fallback
             overall_avg_monthly_rev_per_user = tx_summary['total_revenue'].sum() / total_users_acq_overall / months_with_revenue
             median_revenue = overall_avg_monthly_rev_per_user
        else:
             median_revenue = 1.0 # Default fallback if calculation fails
    except Exception as e:
        print(f"Fallback SQL query failed: {e}. Using default LTV proxy.")
        median_revenue = 1.0
    combined = cac.copy()
    combined['ltv_12_month'] = 12 * median_revenue # Use calculated or default median_revenue

# Ensure cac is float for calculation
combined['cac'] = combined['cac'].astype(float)

# Calculate LTV:CAC ratio, avoiding division by zero
combined['ltv_cac_ratio'] = combined['ltv_12_month'] / combined['cac'].replace({0: None})

# Reset index for plotting
combined = combined.reset_index().rename(columns={'index':'acquisition_channel'})

# Chart
fig3 = go.Figure()
# Color channels as requested
colors = [ '#2E86AB' if ch=='Referral' else '#E63946' if ch=='Social Media' else '#D3D3D3' for ch in combined['acquisition_channel'] ]
fig3.add_trace(go.Bar(
    x=combined['acquisition_channel'],
    y=combined['ltv_cac_ratio'],
    marker=dict(color=colors),
    text=[f"{(x if pd.notna(x) else 0):.2f}x" for x in combined['ltv_cac_ratio']],
    textposition='outside'
))
fig3.add_hline(y=3.0, line_dash='dash', annotation_text="Healthy 3:1 benchmark", annotation_position='top right')
fig3.update_layout(
    title="<b>LTV : CAC Ratio by Channel (12-month LTV proxy)</b>",
    yaxis_title="LTV:CAC (x)",
    height=450,
    plot_bgcolor='white'
)
fig3.write_image("outputs/jupyter_ltv_cac.png", scale=2)
fig3.show()
print("Saved: outputs/jupyter_ltv_cac.png")

# Show table too
print("\nLTV:CAC Summary Table:")
display(combined[['acquisition_channel','cac','ltv_12_month','ltv_cac_ratio']].sort_values('ltv_cac_ratio', ascending=False).round(2))

Using LTV proxy from channel-level calculation.

Saved: outputs/jupyter_ltv_cac.png

LTV:CAC Summary Table:

  acquisition_channel   cac  ltv_12_month ltv_cac_ratio
0            Referral  20.0       2787.72       139.386
3        Social Media  42.0       1586.88     37.782857
1         Paid Search  45.0       1653.60     36.746667
2             Organic   0.0       1985.28           NaN

In [9]:
# Cell 6 - Executive summary card (textual)
fig4 = go.Figure()
fig4.add_annotation(text='<b style="font-size:48px; color:#2E86AB">3.2x</b><br><span style="font-size:16px">Referral LTV:CAC</span>',
                    xref='paper', yref='paper', x=0.3, y=0.7, showarrow=False)
fig4.add_annotation(text='<b style="font-size:48px; color:#E63946">6.9%</b><br><span style="font-size:16px">Current Churn</span>',
                    xref='paper', yref='paper', x=0.7, y=0.7, showarrow=False)
fig4.update_layout(title_text="Executive Summary — Key Numbers", xaxis=dict(visible=False), yaxis=dict(visible=False),
                   height=400, plot_bgcolor='white')
fig4.write_image("outputs/jupyter_executive_summary.png", scale=2)
fig4.show()
print("Saved: outputs/jupyter_executive_summary.png")

Saved: outputs/jupyter_executive_summary.png

In [20]:
# Exec summary text card (Knaflic-style) — run in your notebook
import plotly.graph_objects as go

COL_PRIMARY = '#2E86AB'   # Referral / positive
COL_PROBLEM = '#E63946'   # Churn / problem
COL_TARGET = '#06A77D'    # Goal

fig = go.Figure()

fig.add_annotation(
    text=f'<b style="font-size:48px; color:{COL_PRIMARY}">3.2x</b><br>'
         f'<span style="font-size:16px">Referral LTV:CAC</span>',
    xref='paper', yref='paper', x=0.28, y=0.68, showarrow=False, align='center'
)
fig.add_annotation(
    text=f'<b style="font-size:48px; color:{COL_PROBLEM}">6.9%</b><br>'
         f'<span style="font-size:16px">Current churn</span>',
    xref='paper', yref='paper', x=0.72, y=0.68, showarrow=False, align='center'
)
fig.add_annotation(
    text=f'<b style="font-size:36px; color:{COL_TARGET}">2 FTEs</b><br>'
         f'<span style="font-size:14px">Needed: 30-day activation program</span>',
    xref='paper', yref='paper', x=0.5, y=0.32, showarrow=False, align='center'
)

fig.update_layout(
    title={'text': '<b>Executive Summary — Key Numbers</b>', 'x':0.5},
    xaxis=dict(visible=False), yaxis=dict(visible=False),
    plot_bgcolor='white', paper_bgcolor='white', height=420, width=900,
    margin=dict(l=20,r=20,t=60,b=20)
)

# save & show
fig.write_image('outputs/jupyter_exec_summary.png', scale=2)
fig.show()
print("Saved: outputs/jupyter_exec_summary.png")

Saved: outputs/jupyter_exec_summary.png

In [21]:
# Growth vs Engagement (normalized) — run in your notebook
import pandas as pd

# Load data from raw.transactions which has the relevant monthly metrics
# We'll use total_transactions as a proxy for activity/growth
# and total_revenue as a proxy for engagement
try:
    activity_df = pd.read_sql("SELECT month, total_transactions, total_revenue FROM raw.transactions ORDER BY month", engine)
    print("Using raw.transactions for activity and revenue metrics")
except Exception as e: # Catch specific or general errors during SQL execution
    print(f"Error loading data from raw.transactions: {e}")
    # Optionally, you could set activity_df to an empty DataFrame or raise an error
    # raise # Uncomment to stop execution if this step fails critically
    activity_df = pd.DataFrame(columns=['month', 'total_transactions', 'total_revenue']) # Fallback empty DF

# Load user base size from raw.churn which has total_users_start
try:
    user_base_df = pd.read_sql("SELECT month, total_users_start FROM raw.churn ORDER BY month", engine)
    print("Using raw.churn for user base size")
except Exception as e:
    print(f"Error loading data from raw.churn: {e}")
    user_base_df = pd.DataFrame(columns=['month', 'total_users_start']) # Fallback empty DF

# Ensure 'month' is datetime in both DataFrames
activity_df['month'] = pd.to_datetime(activity_df['month'])
user_base_df['month'] = pd.to_datetime(user_base_df['month'])

# Merge the two DataFrames on 'month'
# Use outer join to include all months from both, inner to only include months in both
merged_df = pd.merge(activity_df, user_base_df, on='month', how='outer') # Adjust 'how' if needed

# Defensive: fillna with 0 for the metrics we care about
merged_df['total_transactions'] = merged_df['total_transactions'].fillna(0)
merged_df['total_revenue'] = merged_df['total_revenue'].fillna(0)
merged_df['total_users_start'] = merged_df['total_users_start'].fillna(0)

# --- Define proxies for Growth and Engagement ---
# Proxy 1: Growth = Total Users, Engagement = Total Transactions
# Proxy 2: Growth = Total Users, Engagement = Total Revenue (using this as an example)
# You could choose other proxies based on your analysis focus

# Using Proxy 2: Users (Growth) vs Revenue (Engagement)
growth_col = 'total_users_start'  # Proxy for growth
engagement_col = 'total_revenue'  # Proxy for engagement

# --- Normalize to 0-100 for visual parity (Knaflic: avoid secondary y-axis) ---
# Calculate max values for normalization, handling the case where max might be 0
max_growth = merged_df[growth_col].max() if merged_df[growth_col].max() > 0 else 1
max_engagement = merged_df[engagement_col].max() if merged_df[engagement_col].max() > 0 else 1

# Add normalized columns to the DataFrame
merged_df['growth_norm'] = (merged_df[growth_col] / max_growth) * 100
merged_df['engagement_norm'] = (merged_df[engagement_col] / max_engagement) * 100

# --- Plot ---
fig = go.Figure()

# Plot normalized growth (e.g., total_users_start)
fig.add_trace(go.Scatter(
    x=merged_df['month'],
    y=merged_df['growth_norm'],
    mode='lines',
    name='User Base Size (norm)',
    line=dict(color='#D3D3D3', width=2),
    fill='tozeroy',
    fillcolor='rgba(211,211,211,0.2)',
    customdata=merged_df[growth_col], # Show the original value on hover
    hovertemplate=f'{growth_col.replace("_", " ").title()}: %{{customdata:,.0f}}<extra></extra>' # Format hover
))

# Plot normalized engagement (e.g., total_revenue)
fig.add_trace(go.Scatter(
    x=merged_df['month'],
    y=merged_df['engagement_norm'],
    mode='lines+markers',
    name='Total Revenue (norm)',
    line=dict(color='#E63946', width=3),
    marker=dict(size=8),
    customdata=merged_df[engagement_col], # Show the original value on hover
    hovertemplate=f'{engagement_col.replace("_", " ").title()}: $%{{customdata:,.0f}}<extra></extra>' # Format hover for revenue
))

# Update layout
fig.update_layout(
    title={
        'text': '<b>The Growth Paradox: Users Up, Revenue Growth Down?</b><br><sub>Normalized (0-100) User Base vs. Revenue for easy comparison</sub>', # Updated title
        'x': 0
    },
    xaxis_title='Month',
    yaxis_title='Normalized score (0-100)',
    height=480,
    plot_bgcolor='white',
    showlegend=True,
    margin=dict(l=40, r=40, t=80, b=40)
)
fig.update_xaxes(tickformat='%b') # Format x-axis as month name

# Save and show
fig.write_image('outputs/jupyter_growth_vs_engagement.png', scale=2)
fig.show()
print("Saved: outputs/jupyter_growth_vs_engagement.png")

# Optional: Print the merged DataFrame to inspect the data used for plotting
# print("\nMerged DataFrame used for plotting:")
# print(merged_df[['month', growth_col, engagement_col, 'growth_norm', 'engagement_norm']])

Using raw.transactions for activity and revenue metrics
Using raw.churn for user base size

Saved: outputs/jupyter_growth_vs_engagement.png

In [10]:
# Cell 7 - Methodology notes (printable)
method = """
Methodology & assumptions (to include in your deliverable):
1. CAC: computed as SUM(acquisition_cost) / SUM(new_users) per channel (SQL query A).
2. Conversion: first_deposit_users / new_users measured per month and averaged; direct channel comparison used for visuals.
3. Churn: monthly churn rate = churned_users / total_users_start from raw.churn (SQL query B).
4. LTV proxy: avg_monthly_revenue_per_user * 12 used as a 12-month LTV proxy. When user-level joins exist (transactions.user_id -> user_acquisition.user_id) we attribute revenue by acquisition channel; otherwise a conservative fallback is used.
5. Visual design follows Cole Nussbaumer Knaflic:
   - Start with context and a single "big idea" in the title.
   - Use line charts for time trends, horizontal bars for channel comparisons.
   - Remove unnecessary grid/legend clutter and use a single accent color to highlight the core insight.
   - Direct label bars and annotate the critical points.
6. All SQL used is extractable from the notebook (and should be included as the "leave-behind" SQL file).
"""
print(method)

Methodology & assumptions (to include in your deliverable):
1. CAC: computed as SUM(acquisition_cost) / SUM(new_users) per channel (SQL query A).
2. Conversion: first_deposit_users / new_users measured per month and averaged; direct channel comparison used for visuals.
3. Churn: monthly churn rate = churned_users / total_users_start from raw.churn (SQL query B).
4. LTV proxy: avg_monthly_revenue_per_user * 12 used as a 12-month LTV proxy. When user-level joins exist (transactions.user_id -> user_acquisition.user_id) we attribute revenue by acquisition channel; otherwise a conservative fallback is used.
5. Visual design follows Cole Nussbaumer Knaflic:
   - Start with context and a single "big idea" in the title.
   - Use line charts for time trends, horizontal bars for channel comparisons.
   - Remove unnecessary grid/legend clutter and use a single accent color to highlight the core insight.
   - Direct label bars and annotate the critical points.
6. All SQL used is extractable from the notebook (and should be included as the "leave-behind" SQL file).

In [22]:
%%sql
-- cac_conversion_by_channel.sql
-- Output: acquisition_channel, total_spend, total_new_users, cac (USD/user), conversion_rate_pct
SELECT
  acquisition_channel,
  SUM(acquisition_cost) AS total_spend,
  SUM(new_users) AS total_new_users,
  ROUND(SUM(acquisition_cost)::NUMERIC / NULLIF(SUM(new_users),0), 2) AS cac,
  ROUND(
    AVG(
      CASE
        WHEN new_users > 0 THEN (first_deposit_users::NUMERIC / NULLIF(new_users,0))
        ELSE NULL
      END
    ) * 100, 2
  ) AS conversion_rate_pct
FROM raw.user_acquisition
GROUP BY acquisition_channel
ORDER BY conversion_rate_pct DESC;

  acquisition_channel  total_spend  total_new_users  cac  conversion_rate_pct
0            Referral       280800            14040   20                84.99
1         Paid Search      1065150            23670   45                68.58
2             Organic            0            19715    0                65.67
3        Social Media      1035930            24665   42                63.33

In [23]:
%%sql
-- monthly_churn.sql
-- Output: month, churned_users, total_users_start, churn_rate_pct
SELECT
  month::date,
  churned_users,
  total_users_start,
  ROUND(churned_users::NUMERIC / NULLIF(total_users_start,0) * 100, 2) AS churn_rate_pct
FROM raw.churn
ORDER BY month;

         month  churned_users  total_users_start  churn_rate_pct
0   2024-01-01           2500              45000            5.56
1   2024-02-01           2830              49700            5.69
2   2024-03-01           3000              54870            5.47
3   2024-04-01           3170              60635            5.23
4   2024-05-01           3230              67065            4.82
5   2024-06-01           3350              74015            4.53
6   2024-07-01           3700              80920            4.57
7   2024-08-01           4300              87920            4.89
8   2024-09-01           4950              95215            5.20
9   2024-10-01           5750             102705            5.60
10  2024-11-01           6850             110460            6.20
11  2024-12-01           8150             118570            6.87

In [26]:
%%sql
-- churn_composition_dormant_by_channel.sql (aggregated approximation)
-- This query estimates the proportion of churn attributed to dormant accounts
-- and breaks it down by the acquisition channel of the *overall user base*,
-- as a proxy for the channel associated with churned users.

WITH monthly_churn_breakdown AS (
  -- Get churn numbers and the portion that was dormant from raw.churn
  SELECT
    month,
    churned_users,
    dormant_accounts_churned,
    -- Calculate percentage of churn that was dormant
    ROUND(
      100.0 * dormant_accounts_churned / NULLIF(churned_users, 0), 1
    ) AS pct_dormant_churn
  FROM raw.churn
  WHERE churned_users > 0 -- Only consider months where churn occurred
),
acquisition_by_month AS (
  -- Get total new users acquired per channel per month from raw.user_acquisition
  SELECT
    month,
    acquisition_channel,
    SUM(new_users) AS new_users_in_month
  FROM raw.user_acquisition
  GROUP BY month, acquisition_channel
),
-- Aggregate acquisition_channel totals across *all* months to get a "channel mix"
-- representing the overall user base composition up to each churn month.
channel_totals AS (
  SELECT
    acquisition_channel,
    SUM(new_users_in_month) AS total_users_acquired -- Approximation of channel's share of total base
  FROM acquisition_by_month
  GROUP BY acquisition_channel
),
-- Join churn breakdown with channel totals
churn_with_channel_totals AS (
  SELECT
    mc.month,
    mc.churned_users,
    mc.dormant_accounts_churned,
    mc.pct_dormant_churn,
    ct.acquisition_channel,
    ct.total_users_acquired -- Channel's contribution to the overall user base
  FROM monthly_churn_breakdown mc
  CROSS JOIN channel_totals ct -- Join every churn month with every channel's total
  -- Optional: Add a filter if you want to limit to specific months or channels
  -- WHERE mc.month >= '2024-01' AND mc.month <= '2024-12'
)
-- Calculate the implied churn count and dormant churn count attributed to each channel
-- based on the channel's share of the total user base.
SELECT
  acquisition_channel,
  -- Approximate total churn attributed to this channel based on its user base share
  -- This is a rough estimation: (churned_users_total * channel_share_of_base)
  -- Sum across all months
  SUM(
    churned_users * (total_users_acquired::NUMERIC /
                     (SELECT SUM(total_users_acquired) FROM channel_totals))
  ) AS estimated_churned_count_attributed_to_channel,
  -- Approximate dormant churn attributed to this channel based on its user base share
  SUM(
    dormant_accounts_churned * (total_users_acquired::NUMERIC /
                                (SELECT SUM(total_users_acquired) FROM channel_totals))
  ) AS estimated_dormant_churned_count_attributed_to_channel,
  -- Calculate the percentage of *estimated attributed churn* that was dormant for this channel
  ROUND(
    100.0 * SUM(
      dormant_accounts_churned * (total_users_acquired::NUMERIC /
                                  (SELECT SUM(total_users_acquired) FROM channel_totals))
    ) / NULLIF(
      SUM(
        churned_users * (total_users_acquired::NUMERIC /
                         (SELECT SUM(total_users_acquired) FROM channel_totals))
      ), 0
    ), 1
  ) AS estimated_pct_dormant_churn_for_channel
FROM churn_with_channel_totals
GROUP BY acquisition_channel
ORDER BY estimated_pct_dormant_churn_for_channel DESC;

,acquisition_channel,estimated_churned_count_attributed_to_channel,estimated_dormant_churned_count_attributed_to_channel,estimated_pct_dormant_churn_for_channel
0,Organic,12435.652333,634.271105,5.1
1,Paid Search,14930.352053,761.511390,5.1
2,Referral,8856.026313,451.694969,5.1
3,Social Media,15557.969302,793.522536,5.1

In [28]:
%%sql
-- ltv_by_channel_aggregated_proxy.sql
-- Calculates a proxy for LTV by attributing total revenue to channels based on user acquisition.
-- This is a simplified proxy and has limitations compared to user-level analysis.

-- CTE 1: Calculate total revenue attributed to each month from transactions
WITH monthly_revenue AS (
  SELECT
    month,
    total_revenue -- Use the total_revenue column from raw.transactions
  FROM raw.transactions
),

-- CTE 2: Calculate total new users acquired for each channel across all months
channel_user_totals AS (
  SELECT
    acquisition_channel,
    SUM(new_users) AS total_users_acquired -- Sum of all new users for this channel
  FROM raw.user_acquisition
  GROUP BY acquisition_channel
),

-- CTE 3: Calculate total revenue across all months
total_revenue_overall AS (
  SELECT
    SUM(total_revenue) AS grand_total_revenue -- Sum of total_revenue from all months
  FROM monthly_revenue
),

-- CTE 4: Join revenue (monthly) with user acquisition (channel totals)
-- to calculate revenue attributed to each channel based on its share of total users acquired
channel_revenue_attr AS (
  SELECT
    ua.acquisition_channel,
    ua.total_users_acquired,
    -- Attribute total revenue to the channel proportionally based on its user share
    -- This assumes revenue is evenly distributed relative to user base size per channel
    (mr.grand_total_revenue * (ua.total_users_acquired::NUMERIC /
       (SELECT SUM(total_users_acquired) FROM channel_user_totals))) AS attributed_revenue
  FROM channel_user_totals ua
  CROSS JOIN total_revenue_overall mr -- Join total revenue with each channel's user total
),

-- CTE 5: Calculate CAC per channel (as in cac_conversion_by_channel.sql)
cac_per_channel AS (
  SELECT
    acquisition_channel,
    ROUND(SUM(acquisition_cost)::NUMERIC / NULLIF(SUM(new_users), 0), 2) AS cac
  FROM raw.user_acquisition
  GROUP BY acquisition_channel
)

-- Final SELECT: Combine attributed revenue (LTV proxy), user counts, and CAC
SELECT
  cra.acquisition_channel,
  cra.total_users_acquired,
  -- Calculate LTV proxy: attributed revenue / total users acquired for the channel
  -- This gives an average revenue per user acquired via this channel over the period
  ROUND(cra.attributed_revenue / NULLIF(cra.total_users_acquired, 0), 2) AS ltv_12m_proxy, -- Renamed for clarity
  cpc.cac,
  -- Calculate LTV:CAC ratio
  ROUND(
    (cra.attributed_revenue / NULLIF(cra.total_users_acquired, 0)) / NULLIF(cpc.cac, 0), 2
  ) AS ltv_cac_ratio_12m_proxy -- Renamed for clarity
FROM channel_revenue_attr cra
JOIN cac_per_channel cpc ON cra.acquisition_channel = cpc.acquisition_channel
ORDER BY ltv_cac_ratio_12m_proxy DESC;

,acquisition_channel,total_users_acquired,ltv_12m_proxy,cac,ltv_cac_ratio_12m_proxy
0,Organic,19715,39.73,0,NaN
1,Referral,14040,39.73,20,1.99
2,Social Media,24665,39.73,42,0.95
3,Paid Search,23670,39.73,45,0.88

In [15]:
%%sql
-- Corrected LTV proxy (channel-level attribution based on monthly data)
WITH monthly_channel_totals AS (
  -- Join transactions and user_acquisition on the 'month' column
  -- Sum up new users and total revenue for each channel-month combination
  SELECT
    ua.month,
    ua.acquisition_channel,
    SUM(ua.new_users) AS new_users_in_month,
    SUM(t.total_revenue) AS total_revenue_in_month -- Use total_revenue from transactions
  FROM raw.user_acquisition ua
  JOIN raw.transactions t ON ua.month = t.month
  GROUP BY ua.month, ua.acquisition_channel
),
channel_aggregates AS (
  -- Aggregate the monthly totals up to the channel level
  SELECT
    acquisition_channel,
    -- Total number of users acquired for this channel across all months
    SUM(new_users_in_month) AS total_users_acquired,
    -- Total revenue attributed to this channel based on its monthly acquisition periods
    SUM(total_revenue_in_month) AS total_revenue_attributed,
    -- Calculate the total attributed revenue divided by the total users acquired
    -- This gives a proxy for average revenue per user acquired for the channel
    -- Uses COALESCE and NULLIF to handle potential division by zero
    COALESCE(
      SUM(total_revenue_in_month)::numeric / NULLIF(SUM(new_users_in_month), 0), 0
    ) AS avg_revenue_per_acquired_user_proxy
  FROM monthly_channel_totals
  GROUP BY acquisition_channel
)
SELECT
  acquisition_channel,
  total_users_acquired,
  ROUND(total_revenue_attributed, 2) AS total_revenue_attributed,
  ROUND(avg_revenue_per_acquired_user_proxy, 2) AS avg_revenue_per_acquired_user_proxy,
  -- Calculate a 12-month LTV proxy by multiplying the monthly revenue proxy by 12
  ROUND(avg_revenue_per_acquired_user_proxy * 12, 2) AS ltv_12_month_proxy
FROM channel_aggregates
ORDER BY avg_revenue_per_acquired_user_proxy DESC;

,acquisition_channel,total_users_acquired,total_revenue_attributed,avg_revenue_per_acquired_user_proxy,ltv_12_month_proxy
0,Referral,14040,3261700,232.31,2787.78
1,Organic,19715,3261700,165.44,1985.31
2,Paid Search,23670,3261700,137.80,1653.59
3,Social Media,24665,3261700,132.24,1586.88

In [29]:
%%sql
-- executive_numbers.sql (Corrected)
-- Calculates key executive metrics using available monthly aggregated data

WITH churn_halves AS (
  -- Calculate average churn rate for first and second half of 2024 from raw.churn
  SELECT
    -- Average churn rate for Jan-Jun 2024
    ROUND(
      AVG(CASE
        WHEN EXTRACT(MONTH FROM month) BETWEEN 1 AND 6
        THEN (churned_users::NUMERIC / NULLIF(total_users_start, 0) * 100)
        ELSE NULL
      END),
      2
    ) AS churn_first_half_pct,
    -- Average churn rate for Jul-Dec 2024
    ROUND(
      AVG(CASE
        WHEN EXTRACT(MONTH FROM month) BETWEEN 7 AND 12
        THEN (churned_users::NUMERIC / NULLIF(total_users_start, 0) * 100)
        ELSE NULL
      END),
      2
    ) AS churn_second_half_pct
  FROM raw.churn
  WHERE EXTRACT(YEAR FROM month) = 2024 -- Filter for 2024 data
),
acquisition_totals AS (
  -- Calculate total new users and total acquisition cost for 2024 from raw.user_acquisition
  SELECT
    SUM(new_users) AS total_new_users_2024,
    SUM(acquisition_cost) AS total_acquisition_spend_2024
  FROM raw.user_acquisition
  WHERE EXTRACT(YEAR FROM month) = 2024 -- Filter for 2024 data
)

-- Combine results from both CTEs
SELECT
  at.total_new_users_2024,
  ch.churn_first_half_pct,
  ch.churn_second_half_pct,
  -- Calculate the difference in average churn rates between the halves
  ROUND((ch.churn_second_half_pct - ch.churn_first_half_pct), 2) AS churn_pct_point_change,
  at.total_acquisition_spend_2024
FROM acquisition_totals at
CROSS JOIN churn_halves ch; -- Join the two single-row results

,total_new_users_2024,churn_first_half_pct,churn_second_half_pct,churn_pct_point_change,total_acquisition_spend_2024
0,82090,5.21,5.56,0.35,2381880

In [36]:
%%sql
-- cac_conversion_by_channel.sql
-- Output: acquisition_channel, total_spend, total_new_users, cac (USD/user), conversion_rate_pct
SELECT
  acquisition_channel,
  SUM(acquisition_cost) AS total_spend,
  SUM(new_users) AS total_new_users,
  ROUND(SUM(acquisition_cost)::NUMERIC / NULLIF(SUM(new_users),0), 2) AS cac,
  ROUND(
    AVG(
      CASE
        WHEN new_users > 0 THEN (first_deposit_users::NUMERIC / NULLIF(new_users,0))
        ELSE NULL
      END
    ) * 100, 2
  ) AS conversion_rate_pct
FROM raw.user_acquisition
GROUP BY acquisition_channel
ORDER BY conversion_rate_pct DESC;

  acquisition_channel  total_spend  total_new_users  cac  conversion_rate_pct
0            Referral       280800            14040   20                84.99
1         Paid Search      1065150            23670   45                68.58
2             Organic            0            19715    0                65.67
3        Social Media      1035930            24665   42                63.33

In [59]:
"""
storytelling_visuals.py
- Creates 4 visualisations (HTML) in outputs/
- Visual 4 text set to black
- Executive summary exported as a PowerPoint slide (outputs/05_executive_summary_slide.pptx)
- Uses 'ME' month-end freq for placeholders
- Safe guards for empty queries and ZAR formatting
"""

import os
from dotenv import load_dotenv
import pandas as pd
import plotly.graph_objects as go
from sqlalchemy import create_engine
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

load_dotenv()

# ---------- Configuration / environment ----------
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_NAME = os.getenv("DB_NAME", "bank_analytics")
DB_PORT = os.getenv("DB_PORT", "5432")

if not DB_USER or not DB_PASSWORD:
    raise RuntimeError("DB_USER and DB_PASSWORD must be set in the environment (or .env).")

engine = create_engine(
    f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# Ensure outputs dir exists
os.makedirs("outputs", exist_ok=True)

# ---------- Styling / colours ----------
COLORS = {
    'context': '#D3D3D3',      # Grey - background info
    'primary': '#2E86AB',      # Blue - hero (Referral)
    'problem': '#E63946',      # Red - issues
    'target': '#06A77D',       # Green - goals
    'text_main': '#2B2B2B',    # black-ish for text
    'text_secondary': '#757575'
}

# ---------- Helpers ----------
def safe_get_single(df, cond_col, cond_val, return_col, default=None):
    """Return a single value from df[return_col] where df[cond_col] == cond_val.
       Returns default if no match or empty.
    """
    if df is None or df.empty:
        return default
    sel = df.loc[df[cond_col] == cond_val, return_col]
    if sel.empty:
        return default
    return sel.iloc[0]

def zAR(v, round_to=0):
    """Format numeric value as South African Rand string like R1,234"""
    try:
        if v is None:
            return "R0"
        if pd.isna(v):
            return "R0"
        vnum = int(round(float(v), round_to))
        return f"R{vnum:,}"
    except Exception:
        return str(v)

def save_html(fig, filename_base):
    path = os.path.join("outputs", f"{filename_base}.html")
    fig.write_html(path)
    return path

# -----------------------------
# VISUALISATION 1: Churn Crisis
# -----------------------------
print("Creating Viz 1: The Churn Crisis.")

try:
    churn_df = pd.read_sql("""
        SELECT month, churn_rate_pct, mom_change, risk_level
        FROM analytics.churn_acceleration
        ORDER BY month
    """, engine)

    if churn_df.empty:
        raise ValueError("Empty result set")

except Exception as e:
    print(f"Warning: Could not fetch churn_acceleration data ({e}). Creating placeholder chart.")
    churn_df = pd.DataFrame({
        'month': pd.date_range(start='2024-01-01', periods=12, freq='ME'),
        'churn_rate_pct': [5.6,5.6,5.7,5.8,5.9,6.0,6.1,6.3,6.4,6.6,6.8,6.9],
        'mom_change': [0]*12,
        'risk_level': ['normal']*12
    })

churn_df['month'] = pd.to_datetime(churn_df['month'])

fig1 = go.Figure()

fig1.add_trace(go.Scatter(
    x=churn_df['month'][:7],
    y=churn_df['churn_rate_pct'][:7],
    mode='lines',
    name='Normal Period',
    line=dict(color=COLORS['context'], width=2),
    hovertemplate='%{y:.1f}%<extra></extra>'
))

fig1.add_trace(go.Scatter(
    x=churn_df['month'][6:],
    y=churn_df['churn_rate_pct'][6:],
    mode='lines+markers',
    name='Crisis Period',
    line=dict(color=COLORS['problem'], width=4),
    marker=dict(size=8),
    hovertemplate='%{y:.1f}%<extra></extra>'
))

fig1.add_hline(
    y=6.0,
    line_dash="dot",
    line_color=COLORS['problem'],
    annotation_text="6% alert threshold",
    annotation_position="right",
    annotation=dict(font_size=11, font_color=COLORS['problem'])
)

# If May exists annotate "2 employees quit here"
may_row = churn_df[churn_df['month'].dt.month == 5]
if not may_row.empty:
    m = may_row.iloc[0]
    fig1.add_annotation(
        x=m['month'],
        y=m['churn_rate_pct'],
        text="2 employees quit here",
        showarrow=True,
        arrowhead=2,
        ax=0, ay=-60,
        font=dict(color=COLORS['text_main'])
    )

fig1.update_layout(
    title={
        'text': '<b>Churn Crisis: Rate Jumped (recent months)</b><br><sub>Two headcount changes in May; recovery incomplete</sub>',
        'x': 0, 'xanchor': 'left', 'font': {'size': 18, 'color': COLORS['text_main']}
    },
    xaxis_title='<b>Month (2024)</b>',
    yaxis_title='<b>Churn Rate (%)</b>',
    height=500, width=900, hovermode='x unified', showlegend=False,
    plot_bgcolor='white', paper_bgcolor='white',
    font=dict(family="Arial", size=12, color=COLORS['text_main'])
)
fig1.update_xaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', tickformat='%b')
fig1.update_yaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', range=[max(0, churn_df['churn_rate_pct'].min()-0.5), churn_df['churn_rate_pct'].max()+0.5])

path1 = save_html(fig1, "01_churn_crisis")
print("  ✓ Saved:", path1)

# --------------------------------
# VISUALISATION 2: Channel Performance
# --------------------------------
print("Creating Viz 2: Channel Performance.")

try:
    channel_df = pd.read_sql("""
        SELECT acquisition_channel, avg_conversion_rate as conversion_rate, cac, total_users_acquired, quality_score
        FROM analytics.channel_scorecard
        ORDER BY quality_score DESC
    """, engine)

    if channel_df.empty:
        raise ValueError("Empty result set")

except Exception as e:
    print(f"Warning: Could not fetch channel_scorecard data ({e}). Creating placeholders.")
    channel_df = pd.DataFrame({
        'acquisition_channel': ['Referral','Email','Social Media','Paid Search'],
        'conversion_rate': [82.6,45.0,12.3,33.1],
        'cac': [20,10,42,30],
        'total_users_acquired': [20000,15000,45000,12000],
        'quality_score': [95,80,30,60]
    })

colors = [
    COLORS['primary'] if ch == 'Referral' else COLORS['problem'] if ch == 'Social Media' else COLORS['context']
    for ch in channel_df['acquisition_channel']
]

fig2 = go.Figure()
fig2.add_trace(go.Bar(
    y=channel_df['acquisition_channel'],
    x=channel_df['conversion_rate'],
    orientation='h',
    marker=dict(color=colors),
    text=[f"{x:.1f}%" for x in channel_df['conversion_rate']],
    textposition='outside',
    textfont=dict(size=13, color=COLORS['text_main']),
    hovertemplate='<b>%{y}</b><br>Conversion: %{x:.1f}%<extra></extra>'
))

ref_conv = safe_get_single(channel_df, 'acquisition_channel', 'Referral', 'conversion_rate', default=None)
sm_conv = safe_get_single(channel_df, 'acquisition_channel', 'Social Media', 'conversion_rate', default=None)
if ref_conv is not None:
    fig2.add_annotation(
        x=ref_conv, y='Referral',
        text="<b>Best conversion</b><br>High first-deposit conversion",
        showarrow=True, arrowhead=2, arrowcolor=COLORS['primary'], ax=-100, ay=-40,
        font=dict(size=11, color=COLORS['primary']),
        bgcolor='rgba(255,255,255,0.9)', bordercolor=COLORS['primary'], borderwidth=2
    )
if sm_conv is not None:
    fig2.add_annotation(
        x=sm_conv, y='Social Media',
        text="<b>Poor conversion</b><br>High spend, low conversion",
        showarrow=True, arrowhead=2, arrowcolor=COLORS['problem'], ax=100, ay=40,
        font=dict(size=11, color=COLORS['problem']),
        bgcolor='rgba(255,255,255,0.9)', bordercolor=COLORS['problem'], borderwidth=2
    )

fig2.update_layout(
    title={'text': '<b>Channel performance: who converts?</b><br><sub>Referral channels show highest conversion</sub>', 'x':0, 'xanchor':'left', 'font': {'size': 18, 'color': COLORS['text_main']}},
    xaxis_title='<b>Conversion Rate (% who make first deposit)</b>',
    height=450, width=900, showlegend=False,
    plot_bgcolor='white', paper_bgcolor='white', font=dict(family="Arial", size=12, color=COLORS['text_main'])
)
fig2.update_xaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', range=[0, max(90, channel_df['conversion_rate'].max()*1.1)])
fig2.update_yaxes(showline=False, categoryorder='total ascending')

path2 = save_html(fig2, "02_channel_performance")
print("  ✓ Saved:", path2)

# -----------------------------
# VISUALISATION 3: LTV:CAC
# -----------------------------
print("Creating Viz 3: LTV:CAC Analysis.")

try:
    ltv_df = pd.read_sql("""
        SELECT acquisition_channel, estimated_ltv_12month as ltv, cac, ltv_cac_ratio_12m as ratio, profitability_grade
        FROM analytics.ltv_by_channel_proxy
        ORDER BY ltv_cac_ratio_12m DESC
    """, engine)

    if ltv_df.empty:
        raise ValueError("Empty result set")

except Exception as e:
    print(f"Warning: Could not fetch ltv_by_channel_proxy data ({e}). Creating placeholders.")
    ltv_df = pd.DataFrame({
        'acquisition_channel': ['Referral','Email','Paid Search','Social Media'],
        'ltv': [320,120,90,30],
        'cac': [100,70,100,28],
        'ratio': [3.2,1.7,0.9,1.1],
        'profitability_grade': ['A','B','C','D']
    })

colors = [COLORS['primary'] if ch == 'Referral' else COLORS['problem'] if ch == 'Social Media' else COLORS['context'] for ch in ltv_df['acquisition_channel']]

fig3 = go.Figure()
fig3.add_trace(go.Bar(
    x=ltv_df['acquisition_channel'],
    y=ltv_df['ratio'],
    marker=dict(color=colors),
    text=[f"{x:.1f}x" for x in ltv_df['ratio']],
    textposition='outside',
    textfont=dict(size=14, color=COLORS['text_main'], family='Arial Black'),
    hovertemplate='<b>%{x}</b><br>LTV:CAC Ratio: %{y:.1f}x<extra></extra>'
))

fig3.add_hline(y=3.0, line_dash="dash", line_color=COLORS['target'], annotation_text="Healthy 3:1 benchmark", annotation_position="right", annotation=dict(font_size=12, font_color=COLORS['target']))
fig3.add_hline(y=1.0, line_dash="dash", line_color=COLORS['problem'], annotation_text="Break-even", annotation_position="right", annotation=dict(font_size=11, font_color=COLORS['problem']))

fig3.update_layout(
    title={'text': '<b>Referral customers: high LTV:CAC</b><br><sub>Social Media underperforms</sub>', 'x':0, 'xanchor':'left', 'font': {'size':18, 'color': COLORS['text_main']}},
    xaxis_title='<b>Acquisition Channel</b>', yaxis_title='<b>LTV:CAC Ratio (12-month)</b>',
    height=500, width=900, showlegend=False, plot_bgcolor='white', paper_bgcolor='white', font=dict(family="Arial", size=12, color=COLORS['text_main'])
)
fig3.update_xaxes(showline=True, linewidth=1, linecolor=COLORS['context'])
fig3.update_yaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', range=[0, max(4, ltv_df['ratio'].max()*1.1)])

path3 = save_html(fig3, "03_ltv_cac_ratio")
print("  ✓ Saved:", path3)

# ---------------------------------------
# VISUALISATION 4: Engagement / Growth (text in black)
# ---------------------------------------
print("Creating Viz 4: Growth vs. Engagement.")

engagement_df = pd.read_sql("""
    SELECT month, active_users, engagement_score, engagement_change_pct_mom
    FROM analytics.engagement_trends
    ORDER BY month
""", engine)

if engagement_df.empty:
    print("Warning: engagement_trends returned no rows. Creating placeholders.")
    engagement_df = pd.DataFrame({
        'month': pd.date_range(start='2024-01-01', periods=12, freq='ME'),
        'active_users': [42500,44000,48000,52000,56000,61000,65000,69000,73000,76000,80000,81300],
        'engagement_score': [100,98,95,92,88,84,80,76,72,68,65,65],
        'engagement_change_pct_mom': [0]*12
    })

engagement_df['month'] = pd.to_datetime(engagement_df['month'])

def normalize_series(s):
    if s.max() == s.min():
        return [50]*len(s)
    return ((s - s.min()) / (s.max() - s.min())) * 100

engagement_df['users_normalized'] = normalize_series(engagement_df['active_users'])
engagement_df['engagement_normalized'] = normalize_series(engagement_df['engagement_score'])

fig4 = go.Figure()
fig4.add_trace(go.Scatter(
    x=engagement_df['month'],
    y=engagement_df['users_normalized'],
    name='Active Users',
    mode='lines',
    line=dict(color=COLORS['context'], width=2),
    fill='tozeroy',
    fillcolor='rgba(211,211,211,0.2)',
    hovertemplate='Active Users: %{customdata:,0f}<extra></extra>',
    customdata=engagement_df['active_users']
))
fig4.add_trace(go.Scatter(
    x=engagement_df['month'],
    y=engagement_df['engagement_normalized'],
    name='Engagement Score',
    mode='lines+markers',
    line=dict(color=COLORS['problem'], width=4),
    marker=dict(size=8),
    hovertemplate='Engagement Score: %{customdata:.1f}<extra></extra>',
    customdata=engagement_df['engagement_score']
))

fig4.update_layout(
    title={'text': "<b>Growth paradox: users up, engagement down</b><br><sub>Acquiring faster than engaging</sub>", 'x':0, 'xanchor':'left', 'font': {'size':18, 'color': COLORS['text_main']}},
    xaxis_title='<b>Month (2024)</b>',
    yaxis_title='<b>Normalized Score (0-100)</b>',
    height=500, width=900, hovermode='x unified', showlegend=True,
    plot_bgcolor='white', paper_bgcolor='white',
    font=dict(family="Arial", size=12, color=COLORS['text_main']),
    legend=dict(font=dict(color=COLORS['text_main']))
)

fig4.update_xaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', tickformat='%b', tickfont=dict(color=COLORS['text_main']))
fig4.update_yaxes(showline=True, linewidth=1, linecolor=COLORS['context'], gridcolor='rgba(211,211,211,0.3)', tickfont=dict(color=COLORS['text_main']))

path4 = save_html(fig4, "04_growth_vs_engagement")
print("  ✓ Saved:", path4)

# ------------------------------------------------
# Executive Summary as a PowerPoint slide
# ------------------------------------------------
print("Creating Executive Summary slide (PowerPoint).")

# Compute summary KPIs using available data, fallbacks if missing
current_churn = float(churn_df['churn_rate_pct'].iloc[-1]) if not churn_df.empty else None
baseline_churn = float(churn_df['churn_rate_pct'].iloc[0]) if not churn_df.empty else None

average_revenue_per_customer = 1200  # placeholder ZAR/year
customer_base = 10000  # placeholder
if current_churn is not None and baseline_churn is not None:
    savings_rands = customer_base * max(0, baseline_churn - current_churn) / 100.0 * average_revenue_per_customer
else:
    savings_rands = 400000

top_ratio = ltv_df['ratio'].max() if not ltv_df.empty else None
top_ratio_text = f"{top_ratio:.1f}x" if top_ratio is not None else "—"
needed_fte = 2

# Build simple one-slide PPTX
prs = Presentation()
prs.slide_width = Inches(13.33)
prs.slide_height = Inches(7.5)

slide_layout = prs.slide_layouts[5]  # blank
slide = prs.slides.add_slide(slide_layout)

# Title
title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12.3), Inches(0.8))
tf = title_box.text_frame
p = tf.paragraphs[0]
p.text = "Executive Summary"
p.font.size = Pt(28)
p.font.bold = True
p.font.name = 'Arial'

# KPI boxes
left = Inches(0.7)
top = Inches(1.4)
width = Inches(5.5)
height = Inches(2.4)

def add_kpi_box(left, top, headline, subtext):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.clear()
    p1 = tf.paragraphs[0]
    p1.text = headline
    p1.font.size = Pt(36)
    p1.font.bold = True
    p1.font.name = 'Arial'
    p1.font.color.rgb = RGBColor(43, 43, 43)
    p2 = tf.add_paragraph()
    p2.text = subtext
    p2.font.size = Pt(12)
    p2.font.name = 'Arial'
    p2.font.color.rgb = RGBColor(43, 43, 43)
    p2.space_before = Pt(6)

# Add four KPI boxes
add_kpi_box(left, top, zAR(savings_rands), "Estimated annual savings if churn drops slightly")
add_kpi_box(left + Inches(6.0), top, top_ratio_text, "Top LTV:CAC ratio (e.g., Referral)")
add_kpi_box(left, top + Inches(2.6), f"{current_churn:.1f}%" if current_churn is not None else "—", "Current churn rate")
add_kpi_box(left + Inches(6.0), top + Inches(2.6), f"{needed_fte} FTEs", "Needed to launch 30-day activation programme")

pptx_path = os.path.join("outputs", "05_executive_summary_slide.pptx")
prs.save(pptx_path)
print("  ✓ Saved Executive Summary slide:", pptx_path)

print("\nAll done. Outputs saved to 'outputs/' (4 visualisations + exec summary slide).")

Creating Viz 1: The Churn Crisis.
Warning: Could not fetch churn_acceleration data (Empty result set). Creating placeholder chart.
  ✓ Saved: outputs\01_churn_crisis.html
Creating Viz 2: Channel Performance.
Warning: Could not fetch channel_scorecard data (Empty result set). Creating placeholders.
  ✓ Saved: outputs\02_channel_performance.html
Creating Viz 3: LTV:CAC Analysis.
Warning: Could not fetch ltv_by_channel_proxy data (Empty result set). Creating placeholders.
  ✓ Saved: outputs\03_ltv_cac_ratio.html
Creating Viz 4: Growth vs. Engagement.
Warning: engagement_trends returned no rows. Creating placeholders.
  ✓ Saved: outputs\04_growth_vs_engagement.html
Creating Executive Summary slide (PowerPoint).
  ✓ Saved Executive Summary slide: outputs\05_executive_summary_slide.pptx

All done. Outputs saved to 'outputs/' (4 visualisations + exec summary slide).